repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        types_or: [python]
        args: [--fix]
      - id: ruff-format
        types_or: [python]

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--manifest-path, sonia-emu/emulator/Cargo.toml]
        pass_filenames: false
      - id: clippy
        args: [--manifest-path, sonia-emu/emulator/Cargo.toml, --, -D, warnings]
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, html, css]